Génération du journal du 02/03/2026 au 05/03/2026 via Groq...
Erreur lors de l'appel à l'API Groq : Error code: 413 - {'error': {'message': 'Request too large for model `llama-3.3-70b-versatile` in organization `org_01kjz4p4f8expsx6kw3xze0jzc` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Requested 25566, please reduce your message size and try again. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Error: Process completed with exit code 1.
